//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przychodnia.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PRZYCHODNIAEntities : DbContext
    {
        public PRZYCHODNIAEntities()
            : base("name=PRZYCHODNIAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ODDZIAL> ODDZIAL { get; set; }
        public virtual DbSet<ODDZIAL_PRACOWNIK> ODDZIAL_PRACOWNIK { get; set; }
        public virtual DbSet<PACJENT> PACJENT { get; set; }
        public virtual DbSet<PLACOWKA> PLACOWKA { get; set; }
        public virtual DbSet<PRACOWNIK> PRACOWNIK { get; set; }
        public virtual DbSet<RECEPTA> RECEPTA { get; set; }
        public virtual DbSet<SALA> SALA { get; set; }
        public virtual DbSet<SPECJALIZACJA> SPECJALIZACJA { get; set; }
        public virtual DbSet<WIZYTA> WIZYTA { get; set; }
        public virtual DbSet<DYZUR> DYZUR { get; set; }
    }
}
