//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przychodnia.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIZYTA
    {
        public int ID_WIZYTA { get; set; }
        public Nullable<System.DateTime> DATA_WIZYTY { get; set; }
        public Nullable<int> ID_SALA { get; set; }
        public Nullable<int> ID_PRACOWNIK { get; set; }
        public Nullable<int> ID_ODDZIAL { get; set; }
        public Nullable<int> ID_PACJENT { get; set; }
        public string UWAGI { get; set; }
    
        public virtual ODDZIAL ODDZIAL { get; set; }
        public virtual PACJENT PACJENT { get; set; }
        public virtual PRACOWNIK PRACOWNIK { get; set; }
        public virtual SALA SALA { get; set; }
    }
}
